package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class addTest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean addTesting;

	public addTest() {
	}

	public java.lang.Boolean getAddTesting() {
		return this.addTesting;
	}

	public void setAddTesting(java.lang.Boolean addTesting) {
		this.addTesting = addTesting;
	}

	public addTest(java.lang.Boolean addTesting) {
		this.addTesting = addTesting;
	}

}