package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class degrader implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean degraded;

	public degrader() {
	}

	public java.lang.Boolean getDegraded() {
		return this.degraded;
	}

	public void setDegraded(java.lang.Boolean degraded) {
		this.degraded = degraded;
	}

	public degrader(java.lang.Boolean degraded) {
		this.degraded = degraded;
	}

}