package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class extendedTemperature implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean extendedTemperaturePassFail;

	public extendedTemperature() {
	}

	public java.lang.Boolean getExtendedTemperaturePassFail() {
		return this.extendedTemperaturePassFail;
	}

	public void setExtendedTemperaturePassFail(
			java.lang.Boolean extendedTemperaturePassFail) {
		this.extendedTemperaturePassFail = extendedTemperaturePassFail;
	}

	public extendedTemperature(java.lang.Boolean extendedTemperaturePassFail) {
		this.extendedTemperaturePassFail = extendedTemperaturePassFail;
	}

}