package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class flowChange implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean flowChanged;

	public flowChange() {
	}

	public java.lang.Boolean getFlowChanged() {
		return this.flowChanged;
	}

	public void setFlowChanged(java.lang.Boolean flowChanged) {
		this.flowChanged = flowChanged;
	}

	public flowChange(java.lang.Boolean flowChanged) {
		this.flowChanged = flowChanged;
	}

}