package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class flowRerunResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean rerunPassFail;

	public flowRerunResult() {
	}

	public java.lang.Boolean getRerunPassFail() {
		return this.rerunPassFail;
	}

	public void setRerunPassFail(java.lang.Boolean rerunPassFail) {
		this.rerunPassFail = rerunPassFail;
	}

	public flowRerunResult(java.lang.Boolean rerunPassFail) {
		this.rerunPassFail = rerunPassFail;
	}

}