package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class guardbanded implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean guardband;

	public guardbanded() {
	}

	public java.lang.Boolean getGuardband() {
		return this.guardband;
	}

	public void setGuardband(java.lang.Boolean guardband) {
		this.guardband = guardband;
	}

	public guardbanded(java.lang.Boolean guardband) {
		this.guardband = guardband;
	}

}