package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class outOfTemp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean outOfTemperature;

	public outOfTemp() {
	}

	public java.lang.Boolean getOutOfTemperature() {
		return this.outOfTemperature;
	}

	public void setOutOfTemperature(java.lang.Boolean outOfTemperature) {
		this.outOfTemperature = outOfTemperature;
	}

	public outOfTemp(java.lang.Boolean outOfTemperature) {
		this.outOfTemperature = outOfTemperature;
	}

}