package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class pastPartHistory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean passFail;

	public pastPartHistory() {
	}

	public java.lang.Boolean getPassFail() {
		return this.passFail;
	}

	public void setPassFail(java.lang.Boolean passFail) {
		this.passFail = passFail;
	}

	public pastPartHistory(java.lang.Boolean passFail) {
		this.passFail = passFail;
	}

}