package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductionYield implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean productionYieldOK;

	public ProductionYield() {
	}

	public java.lang.Boolean getProductionYieldOK() {
		return this.productionYieldOK;
	}

	public void setProductionYieldOK(java.lang.Boolean productionYieldOK) {
		this.productionYieldOK = productionYieldOK;
	}

	public ProductionYield(java.lang.Boolean productionYieldOK) {
		this.productionYieldOK = productionYieldOK;
	}

}