package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class productionOverkill implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Float productionOverkillPercent;

	public productionOverkill() {
	}

	public java.lang.Float getProductionOverkillPercent() {
		return this.productionOverkillPercent;
	}

	public void setProductionOverkillPercent(
			java.lang.Float productionOverkillPercent) {
		this.productionOverkillPercent = productionOverkillPercent;
	}

	public productionOverkill(java.lang.Float productionOverkillPercent) {
		this.productionOverkillPercent = productionOverkillPercent;
	}

}