package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class returnPartDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String serialNumber;
	private java.lang.String customer;

	public returnPartDetail() {
	}

	public java.lang.String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public java.lang.String getCustomer() {
		return this.customer;
	}

	public void setCustomer(java.lang.String customer) {
		this.customer = customer;
	}

	public returnPartDetail(java.lang.String serialNumber,
			java.lang.String customer) {
		this.serialNumber = serialNumber;
		this.customer = customer;
	}

}