package com.individual.dramcustomerreturn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stringentFlow implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean stringentFlowPassFail;

	public stringentFlow() {
	}

	public java.lang.Boolean getStringentFlowPassFail() {
		return this.stringentFlowPassFail;
	}

	public void setStringentFlowPassFail(java.lang.Boolean stringentFlowPassFail) {
		this.stringentFlowPassFail = stringentFlowPassFail;
	}

	public stringentFlow(java.lang.Boolean stringentFlowPassFail) {
		this.stringentFlowPassFail = stringentFlowPassFail;
	}

}